ui: mocha-bdd
browsers:
  - name: internet explorer
    version: 6..latest
  - name: microsoftedge
    version: latest
  - name: safari
    version: 5..latest
  - name: chrome
    version: [26, 30, 35, 40, 45, -1..latest]
  - name: firefox
    version: [10, 20, 30, 40, -1..latest]
  - name: opera
    version: -1..latest
  - name: iphone
    version: latest
  - name: android
    version: latest
